name: Test New Changes
on: 
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  test-new-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache
      - name: Run test suite
        run: yarn test
      - name: Run cli
        run: yarn cli
